name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  elixir_ci:
    name: "Elixir Checks"
    uses: primait/shared-github-actions/.github/workflows/elixir-ci.yml@elixir-ci-v3.1
    with:
      version-file: ".tool-versions"
